# Generated by Django 3.1.4 on 2020-12-22 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(verbose_name=16)),
                ('last_name', models.TextField(verbose_name=16)),
                ('father_name', models.TextField(verbose_name=16)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField(verbose_name=16)),
            ],
        ),
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(verbose_name=32)),
                ('fio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fio')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type')),
            ],
        ),
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name=64)),
                ('fio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fio')),
            ],
        ),
    ]
